### PR TITLE
 1.20.5 update (this commit also includes updating gradle, fabric-loom)

### PR DESCRIPTION
**Pull request by qwqtoday**

### CODE REVIEW

**Comment by qwqtoday** [comment]
ummm you need java 21 for this and of course running on lower versions with java 21 will not work

**Comment by rom1504** [comment]
conflicts with #18 which should we merge?

**Comment by qwqtoday** [comment]
> conflicts with #18 which should we merge?

#18 should be merged first because it sounds more important to me

**Comment by rom1504** [comment]
Ok done, please rebase

**Comment by AlexProgrammerDE** [comment]
This PR can actually be closed. My reduce duplicate code PR also added 1.20.5.

**Comment by AlexProgrammerDE** [comment]
I'll make a PR for 1.21 now.

**Comment by qwqtoday** [comment]
> This PR can actually be closed. My reduce duplicate code PR also added 1.20.5.

Thanks bye

**Pull request closed without merging**
