### PR TITLE
Import all versions

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**

### CODE REVIEW

**Comment by rom1504** [comment]
what do you think about adding some github action ci to show this works ?

**Comment by AlexProgrammerDE** [comment]
sure

**Comment by u9g** [comment]
The different minecraft versions are on different branches, why would this be better?

**Comment by rom1504** [comment]
I think single branch has some advantages, for example it makes it easier to have CI, and to rerun for all versions

but yes remains to be seen if it's fast enough

**Pull request merged**
