### PR TITLE
Fix handling FeatureSet related entities in 1.20.3/4

### LINKED ISSUE #15: Investigate why 1.21 feature entities in 1.20.3/ 1.20.4 have incorrect data.
In 1.20.3 / 1.20.4 the entity data for the Breeze and its wind charge incorrectly get set to type player. I think this may be because while they exist in the code, trying to create the entity to grab its data most likely returns null if the 1.21 FeatureSet is not enable. 

We will need to investigate this and also update the minecraft-data entity.json file for 1.20.3 once we figure it out.

### PR DESCRIPTION
**Pull request by wgaylord**
This adds a 1.20.4 folder (since it requires code changes compared to 1.20.

It also fixes an issue encountered where 1.20.3/4 with its 1.21 feature set would incorrectly mark the Breeze and its wind charge as player type entities.  Fixed #15

### CODE REVIEW

**Comment by extremeheat** [comment]
I guess one of the bad things with moving to folders is that it's now not possible to diff changes anymore

**Comment by wgaylord** [comment]
Changes were https://github.com/PrismarineJS/minecraft-data-generator-server/pull/16/files#diff-258e58166f7beac80cee5ed4e7d2bc423b8cc40aad60dddedab2eaee4611151aR42-R52  and https://github.com/PrismarineJS/minecraft-data-generator-server/pull/16/files#diff-05e22fe6f7722dcb7843bcf78233bceb986c260872797f7d2fe78b6842db081eR33 (GRASS to SHORT_GRASS)

**Comment by extremeheat** [comment]
LGTM, I assume 1.20.2/1.20 doesn't have the experimental features and that's a 1.20.4 thing? I remember you mentioning something about FeatureSets on other versions also.

**Comment by wgaylord** [comment]
Hm/ seems like somehow my fix sort of works, it showing unknow for the Breeze. :/ Maybe I have to enable the feature set still.

**Comment by wgaylord** [comment]
> LGTM, I assume 1.20.2/1.20 doesn't have the experimental features and that's a 1.20.4 thing? I remember you mentioning something about FeatureSets on other versions also.

It does, but its only the villager trading changes and the bundle (which has been in a featureset since it was introduced)

**Comment by wgaylord** [comment]
Actually lets hold off on this, we should figure out how we want to handle Features. Since they could in the future change recipes (other then add new ones), block drops and other things.

**Comment by rom1504** [comment]
What are features? I don't get it

**Comment by wgaylord** [comment]
> What are features? I don't get it

Why you create a world, you can select "Features" which are changes to the game gated behind selections in that menu, for example Bundles, Villager Trading Changes and now 1.21 update. This is part of why the protocol changes so much recently sanpshots are technically for the current main version with the feature for the next update updating.   See https://minecraft.wiki/w/Experimental_Gameplay for more info

**Comment by rom1504** [comment]
Ok sounds like we shouldn't use the 1.21 feature for 1.20.3 data then

**Comment by wgaylord** [comment]
Thats why I removed the server.properties I added at one point.  The other fix here is needed to make Breeze and their Wind Charge (which still show up in the regirsties even with the feature off) show as type unknown instead of type player.

**Comment by rom1504** [comment]
please say when you consider this ready

**Comment by wgaylord** [comment]
It should be ready, since I am not using the feature directly it doesn't affect other generators and still gives the right answers for entities.  Might want to sit a tiny bit on this just to make sure I don't notice any issues before the merge.

**Comment by wgaylord** [comment]
This should be good to go.

**Pull request merged**
