### PR TITLE
Implement collision offsets as well as some new block data

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**

### CODE REVIEW

**Comment by rom1504** [comment]
can you add more information on what new things this makes available ?

**Comment by AlexProgrammerDE** [comment]
Sure, it adds the data: air: whether the block is air, like air, void air and cave air
fallingBlock: whether the block is affected by gravity like anvil, sand, gravel, etc.
replaceable: Whether the block is replaceable, like air, fluids, short grass, etc.
and lastly offset data. That is used in Minecraft for example to offset flowers and blocks randomly. The only two blocks that have a collision box are bamboo and dripstone. The offset is either XZ or XYZ and per block has a max horizontal and vertical offset. If you don't know that offset, you think the collision box is at the wrong place and the server will flag you for incorrect movement. Mineflayer has this issue, I had it too, but after implementing this, everything works as expected.

**Comment by AlexProgrammerDE** [comment]
Phew sounds like a lot of work. What about my other PR to McDataExtracting?

**Comment by rom1504** [comment]
We prefer using Minecraft data generator server yeah

It's a bit of work to get it to mineflayer but if you don't then what's the point to extract the data ?

**Comment by rom1504** [comment]
lot of conflict now, please re open if you want to fix

**Pull request closed without merging**
